services:

  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
  
  backend:
    image: cba-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - PGUSER=postgres
      - PGHOST=postgres-db
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
    depends_on:
      - postgres-db

  nginx:
    image: nginx-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend